// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4all_mod_nopred_blockmod_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4all_mod_nopred_onemod_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4all_mod_pred_blockmod_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4spline_nopred_blockmod_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4spline_nopred_onemod_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4spline_pred_blockmod_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4all_mod_nopred_blockmod_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4all_mod_nopred_blockmod_mod, 0},
    {"_rcpp_module_boot_stan_fit4all_mod_nopred_onemod_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4all_mod_nopred_onemod_mod, 0},
    {"_rcpp_module_boot_stan_fit4all_mod_pred_blockmod_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4all_mod_pred_blockmod_mod, 0},
    {"_rcpp_module_boot_stan_fit4spline_nopred_blockmod_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4spline_nopred_blockmod_mod, 0},
    {"_rcpp_module_boot_stan_fit4spline_nopred_onemod_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4spline_nopred_onemod_mod, 0},
    {"_rcpp_module_boot_stan_fit4spline_pred_blockmod_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4spline_pred_blockmod_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_hier_growth(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
